# Generated by Django 5.0 on 2024-08-11 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_paiement', models.CharField(choices=[('non_paye', 'Non payé'), ('paye', 'Payé'), ('especes_sur_place', 'espèces sur place')], default='Non payé', max_length=30)),
                ('qr_code', models.CharField(max_length=255)),
                ('Utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evenement')),
            ],
            options={
                'unique_together': {('Utilisateur', 'evenement')},
            },
        ),
    ]
