# Generated by Django 5.0 on 2024-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0002_alter_inscription_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_ROOT/qr_codes/'),
        ),
    ]
