# Generated by Django 5.0 on 2024-08-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0003_alter_inscription_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='participated',
            field=models.BooleanField(default=False),
        ),
    ]
