# Generated by Django 5.0 on 2024-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0004_inscription_participated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
