# Generated by Django 5.0 on 2024-08-20 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0005_inscription_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
