# Generated by Django 5.0 on 2024-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0006_inscription_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
