# Generated by Django 5.0 on 2024-08-30 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0008_alter_inscription_date_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField()),
                ('cachet', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
                ('etat', models.CharField(choices=[('non_genere', 'Non généré'), ('genere', 'Généré')], default='Non généré', max_length=30)),
                ('Inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inscription.inscription')),
            ],
        ),
    ]
