# Generated by Django 5.0 on 2024-08-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0009_attestation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attestation',
        ),
    ]
