# Generated by Django 5.0 on 2024-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscription', '0010_delete_attestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
