# Generated by Django 5.0 on 2024-08-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='date_emission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
