# Generated by Django 5.0 on 2024-08-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0002_alter_attestation_date_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attestations/'),
        ),
    ]
