# Generated by Django 5.0.8 on 2024-08-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=255)),
                ('details_lieu', models.TextField()),
                ('public_vise', models.TextField()),
                ('nombre_places', models.IntegerField()),
                ('organisateurs', models.CharField(max_length=255)),
                ('objectifs', models.TextField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('diffusion_directe', models.BooleanField(default=True)),
            ],
        ),
    ]
