# Generated by Django 5.0 on 2024-08-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_evenement_invitation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='url_live',
            field=models.URLField(blank=True, null=True),
        ),
    ]
