# Generated by Django 5.0 on 2024-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_evenement_url_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='url_live',
        ),
        migrations.AddField(
            model_name='evenement',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
