# Generated by Django 5.0 on 2024-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_evenement_url_live_evenement_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='programme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
