# Generated by Django 5.0 on 2024-09-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_evenement_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='live',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
